spring:
  application:
    name: ${APPLICATION_NAME:frutas-api}
  jackson:
    mapper:
      ACCEPT_CASE_INSENSITIVE_ENUMS: true
  main:
    allow-bean-definition-overriding: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      dialect: org.hibernate.dialect.MySQLDialect
      format_sql: false
  datasource:
    url: 'jdbc:mysql://localhost:3306/hortifruti?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC'
    username: teste
    password: teste123
    driver-class-name: com.mysql.cj.jdbc.Driver
